### ISSUE TITLE
Setting priorities, tasks and milestones for TNC BRAT Analyses

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/pyBRAT#98]
@bangen can you please have a look at 'All Basins -Status & Priority' tab of [this spreadsheet](https://docs.google.com/spreadsheets/d/1yrGR4DNWIrMuSd-4fiKc4lBiRx4K5UWy4cmHfkMAVQM/edit#gid=584384841). Please:

- [ ] share access with all techs. and if you can quickly, populate the HUC Code 
- [ ] instruct technicians (@MatthewMeier, @Albonicomt , @kbartelt) to post their updates to (Overall Status, QA/QC Review and Data Generation) that spreadsheet and to respective issue analysis requests here. For example if ticket #97 has five basins in it, each time they get a basin done they should update status in spreadsheet, and post an update as response to the issue along the lines of 'Finished Truckee (16050102) provisional run today' and provide a link to place on Box (only internal link).  
- [x] populate rest of HUC 8 for remainder of 78 (right now we have 1-45 in column C
- [ ] Update (Overall Status, QA/QC Review and Data Generation) for whatever has been done.
- [ ] Post specific tickets (e.g. #97) with 'Analysis' labels and assign to techs and tie to milestones...

You and I can get things going... When @wally-mac returns we can revise.

**Comment by joewheaton** [comment]
@bangen I didn't see this: https://docs.google.com/spreadsheets/d/14EXBvLc6VscY6m48O3hVYDC_1jIYMVe-Tny02BQNkNI/edit?ts=5b3527a5#gid=644297276

We could use that and bring over my columns if you want. Whatever place is fine.

**Comment by wally-mac** [comment]
Thanks @joewheaton and @bangen for setting this status and priority sheet up! We can chat about this and revise as we see fit.

**Comment by wally-mac** [comment]
@bangen , what is the status of this?

**Comment by joewheaton** [comment]
@wally-mac just try and shut this down, but run through it and see if any of things can be referred to existing tickets or should be split out into other tickets.

**Comment by wally-mac** [comment]
I think this has been taken care of.  I'm closing it.
